spring.application.name=merito

spring.main.web-application-type=none

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:4306/abastecimento}
spring.datasource.username=${DB_USERNAME:merito}
spring.datasource.password=${DB_PASSWORD:merito}

spring.jpa.hibernate.ddl-auto=validate
