spring.application.name=merito

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:4306/abastecimento}
spring.datasource.username=${DB_USERNAME:merito}
spring.datasource.password=${DB_PASSWORD:merito}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

springdoc.swagger-ui.url=/openapi.yaml
